trigger: none

resources:
  pipelines:
  - pipeline: HelloWorldBuild
    source: 'BuildPipeline'
    trigger:
      branches:
        include:
        - main

stages:
- stage: Dev
  jobs:
  - deployment: DeployToDev
    pool:
      name: 'MySelfAgent'
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
                Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
                ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
            displayName: 'Install .NET SDK'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: '$(resources.pipeline.HelloWorldBuild.pipelineId)'
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - script: |
              set PATH=$(Agent.ToolsDirectory)/dotnet;%PATH%
              dotnet --version
              dotnet $(System.ArtifactsDirectory)/drop/HelloWorld.dll
            displayName: 'Run HelloWorld'

- stage: Stage
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
  jobs:
  - deployment: DeployToStage
    pool:
      name: 'MySelfAgent'
    environment: 'Stage'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
                Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
                ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
            displayName: 'Install .NET SDK'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: '$(resources.pipeline.HelloWorldBuild.pipelineId)'
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - script: |
              set PATH=$(Agent.ToolsDirectory)/dotnet;%PATH%
              dotnet --version
              dotnet $(System.ArtifactsDirectory)/drop/HelloWorld.dll
            displayName: 'Run HelloWorld'

- stage: Prod
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
  jobs:
  - deployment: DeployToProd
    pool:
      name: 'MySelfAgent'
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
                Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
                ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
            displayName: 'Install .NET SDK'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: '$(resources.pipeline.HelloWorldBuild.pipelineId)'
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - script: |
              set PATH=$(Agent.ToolsDirectory)/dotnet;%PATH%
              dotnet --version
              dotnet $(System.ArtifactsDirectory)/drop/HelloWorld.dll
            displayName: 'Run HelloWorld'

- stage: Sandbox
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - deployment: DeployToSandbox
    pool:
      name: 'MySelfAgent'
    environment: 'Sandbox'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
                Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
                ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
            displayName: 'Install .NET SDK'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: '$(resources.pipeline.HelloWorldBuild.pipelineId)'
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - script: |
              set PATH=$(Agent.ToolsDirectory)/dotnet;%PATH%
              dotnet --version
              dotnet $(System.ArtifactsDirectory)/drop/HelloWorld.dll
            displayName: 'Run HelloWorld'