trigger: none

resources:
  pipelines:
  - pipeline: HelloWorldBuild
    source: 'bilal36529.testing_pipeline'
    trigger:
      branches:
        include:
        - main

variables:
  - group: release-variables

stages:
- stage: Dev
  jobs:
  - deployment: DeployToDev
    pool:
      name: 'MySelfAgent'
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
                Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
                ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
            displayName: 'Install .NET SDK'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: '$(resources.pipeline.HelloWorldBuild.pipelineId)'
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)/Dev'
          - script: |
              set PATH=$(Agent.ToolsDirectory)/dotnet;%PATH%
              dotnet --version
              dotnet $(System.DefaultWorkingDirectory)/Dev/drop/HelloWorld.dll
            displayName: 'Run HelloWorld'

- stage: Stage
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
  jobs:
  - deployment: DeployToStage
    pool:
      name: 'MySelfAgent'
    environment: 'Stage'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
                Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
                ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
            displayName: 'Install .NET SDK'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: '$(resources.pipeline.HelloWorldBuild.pipelineId)'
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)/Stage'
          - script: |
              set PATH=$(Agent.ToolsDirectory)/dotnet;%PATH%
              dotnet --version
              dotnet $(System.DefaultWorkingDirectory)/Stage/drop/HelloWorld.dll
            displayName: 'Run HelloWorld'

- stage: Prod
  condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
  jobs:
  - deployment: DeployToProd
    pool:
      name: 'MySelfAgent'
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
                Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
                ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
            displayName: 'Install .NET SDK'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: '$(resources.pipeline.HelloWorldBuild.pipelineId)'
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.DefaultWorkingDirectory)/Prod'
          - script: |
              set PATH=$(Agent.ToolsDirectory)/dotnet;%PATH%
              dotnet --version
              dotnet $(System.DefaultWorkingDirectory)/Prod/drop/HelloWorld.dll
            displayName: 'Run HelloWorld'

- stage: Sandbox
  condition: eq(variables['Build.Reason'], 'Manual')
  jobs:
  - job: BuildAndDeploy
    pool:
      name: 'MySelfAgent'
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
          Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
          ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
      displayName: 'Install .NET SDK'
    - checkout: git://bilal36529.testing_pipeline@$(SandboxBranch)
    - script: |
        set PATH=$(Agent.ToolsDirectory)/dotnet;%PATH%
        dotnet build --configuration Release
        dotnet publish --configuration Release --output $(System.DefaultWorkingDirectory)/Sandbox/drop
      displayName: 'Build and Publish'
    - script: |
        set PATH=$(Agent.ToolsDirectory)/dotnet;%PATH%
        dotnet --version
        dotnet $(System.DefaultWorkingDirectory)/Sandbox/drop/HelloWorld.dll
      displayName: 'Run HelloWorld'