parameters:
- name: environment
  type: string
  default: 'Dev'
  values:
  - Dev
  - Stage
  - Prod
  - Sandbox

trigger: none

pool:
  name: 'MySelfAgent'

variables:
  ${{ if eq(parameters.environment, 'Dev') }}:
    artifactName: 'DevArtifact'
  ${{ if eq(parameters.environment, 'Stage') }}:
    artifactName: 'StageArtifact'
  ${{ if eq(parameters.environment, 'Prod') }}:
    artifactName: 'StageArtifact'
  ${{ if eq(parameters.environment, 'Sandbox') }}:
    artifactName: 'drop'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
      Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
      ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
  displayName: 'Install .NET SDK'

- download: current
  artifact: $(artifactName)
  displayName: 'Download ${{ parameters.environment }} Artifact'

- script: |
    set PATH=$(Agent.ToolsDirectory)/dotnet;%PATH%
    dotnet --version
    echo "Running Hello World from ${{ parameters.environment }} environment"
    dotnet $(Pipeline.Workspace)/$(artifactName)/HelloWorld.dll
  displayName: 'Run Hello World from ${{ parameters.environment }}'