parameters:
- name: stage
  type: string
  default: 'Dev'
  values:
  - Dev
  - Stage
  - Prod
  - Sandbox

trigger: none

pool:
  name: 'MySelfAgent'

variables:
  ${{ if eq(parameters.stage, 'Dev') }}:
    artifactPath: '$(System.DefaultWorkingDirectory)/Dev'
  ${{ if eq(parameters.stage, 'Stage') }}:
    artifactPath: '$(System.DefaultWorkingDirectory)/Stage'
  ${{ if eq(parameters.stage, 'Prod') }}:
    artifactPath: '$(System.DefaultWorkingDirectory)/Prod'
  ${{ if eq(parameters.stage, 'Sandbox') }}:
    artifactPath: '$(System.DefaultWorkingDirectory)/Sandbox'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
      Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
      ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
  displayName: 'Install .NET SDK'

- script: |
    set PATH=$(Agent.ToolsDirectory)/dotnet;%PATH%
    dotnet --version
    dotnet $(artifactPath)/drop/HelloWorld.dll
  displayName: 'Run Hello World from ${{ parameters.stage }}'